when:
  - event: push
    branch: master

skip_clone: true

steps:
  - name: clone
    image: fish
    environment:
      REPOSITORY_DIR:
        from_secret: repository_dir
    commands:
      - mkdir -p $REPOSITORY_DIR/$CI_REPO_NAME && cd $REPOSITORY_DIR/$CI_REPO_NAME
      - git clone $CI_REPO_CLONE_SSH_URL (pwd) || git pull --force
      - rmdir $CI_WORKSPACE
      - ln -s $REPOSITORY_DIR/$CI_REPO_NAME $CI_WORKSPACE

  - name: toolchain
    image: fish
    environment:
      RUST_TOOLCHAIN_PATH:
        from_secret: rust_toolchain_path
    commands:
      - rustup toolchain link woodpecker $RUST_TOOLCHAIN_PATH
      - rustup default woodpecker

  - name: build
    image: fish
    environment:
      CARGO_HOME:
        from_secret: cargo_home
      CARGO_TARGET_DIR:
        from_secret: cargo_target_dir
      CARGO_LOG: cargo::core::compiler::fingerprint=info
    commands:
      - cargo build --release --verbose

  - name: PKGBUILD
    image: fish
    environment:
      ARCH_REPO_DIR:
        from_secret: arch_repo_dir
      ARCH_REPO_NAME:
        from_secret: arch_repo_name
      CARGO_TARGET_DIR:
        from_secret: cargo_target_dir
    commands:
      - ln -s $CARGO_TARGET_DIR target
      - makepkg --nodeps
      - mv (makepkg --packagelist) $ARCH_REPO_DIR
      - for pkg in (makepkg --packagelist); repo-add $ARCH_REPO_DIR/$ARCH_REPO_NAME.db.tar.zst $ARCH_REPO_DIR/(string split -r -m 1 '/' $pkg | tail -1); end