when:
  - event: push
    branch: master
  
steps:  
  - name: install-toolchain
    image: fish
    commands:
      - rustup toolchain install stable --profile minimal

  - name: check
    image: fish
    environment:
      CARGO_INCREMENTAL: false
    commands:
      - cargo check
  
  - name: publish (forgejo)
    image: fish
    environment:
      CARGO_INCREMENTAL: false
      CARGO_REGISTRIES_FORGEJO_INDEX:
        from_secret: cargo_registries_forgejo_index
      CARGO_REGISTRIES_FORGEJO_TOKEN:
        from_secret: cargo_registries_forgejo_token
    commands:
      - cargo publish --registry forgejo
    failure: ignore
  
  - name: publish (crates.io)
    image: fish
    environment:
      CARGO_INCREMENTAL: false
      CARGO_REGISTRY_TOKEN:
        from_secret: cargo_registry_token
    commands:
      - cargo publish
    failure: ignore
