when:
  - event: push
    branch: master

skip_clone: true

steps:
  - name: clone
    image: fish
    environment:
      RUST_CI:
        from_secret: rust_ci
      REPOSITORY_DIR:
        from_secret: repository_dir
      CARGO_TARGET_DIR:
        from_secret: cargo_target_dir
    commands:
      - $RUST_CI/clone.fish

  - name: toolchain
    image: fish
    environment:
      RUST_CI:
        from_secret: rust_ci
      RUST_TOOLCHAIN_PATH:
        from_secret: rust_toolchain_path
    commands:
      - $RUST_CI/toolchain.fish

  - name: build
    image: fish
    environment:
      RUST_CI:
        from_secret: rust_ci
      CARGO_HOME:
        from_secret: cargo_home
    commands:
      - $RUST_CI/build.fish

  - name: PKGBUILD
    image: fish
    environment:
      RUST_CI:
        from_secret: rust_ci
      ARCH_REPO_DIR:
        from_secret: arch_repo_dir
      ARCH_REPO_NAME:
        from_secret: arch_repo_name
    commands:
      - $RUST_CI/pkgbuild.fish